// try {
//     //throw new Error('my error')
//     //throw 'error'
//     throw {
//         message: 'error',
//         name: 'myError'
//     }
//
//     console.log("after throw")
// } catch(exception) {
//     console.log('caught: ', exception)
// } finally {
//     console.log('finally')
// }